[package]
name = "jmb-gltf-renderer"
version = "0.1.0"
authors = ["John Michael Bell <johnmichaelbell@gmail.com>"]
edition = "2021"
include = ["LICENSE-APACHE", "LICENSE-MIT", "**/*.rs", "Cargo.toml"]
rust-version = "1.81"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[dependencies]
bytemuck = { version = "1.16.3", features = ["derive"] }
eframe = { version = "0.30.0", default-features = false, features = ["default_fonts", "wgpu", "persistence", "wayland", "x11"] }
egui = "0.30.0"
glam = { version = "0.29.0", features = ["bytemuck", "serde"] }
gltf = { version = "1.4.1", features = ["KHR_lights_punctual", "extensions", "extras"] }
ktx2 = "0.3.0"
log = "0.4"
puffin = { version = "0.19.1", features = ["web"] }
puffin_http = "0.16.1"
serde = { version = "1", features = ["derive"] }
wgpu = "23.0.1"

[build-dependencies]
miette = { version = "7.2.0", features = ["fancy"] }
wgsl_bindgen = "0.15.1"


# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
web-sys = "0.3.70"           # to access the DOM (to hide the loading text)

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
